name: deploy

on:
  push:
    branches: main

env:
  TRT_TAG: "21.10"

jobs:
  main:
    runs-on: ubuntu-latest
    environment: dockerhub
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: projects/gw-iaas/export
        file: projects/gw-iaas/export/Dockerfile
        push: true
        tags: fastml/gw-iaas-export:latest
        build-args: |
          TAG=${{ env.TRT_TAG }}
